<?php

use Illuminate\Database\Seeder;

class ComunaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	DB::table('comunas')->insert(['codigo' => '05602', 'nombre' => 'Algarrobo']);
		DB::table('comunas')->insert(['codigo' => '13502', 'nombre' => 'Alhué']);
		DB::table('comunas')->insert(['codigo' => '08314', 'nombre' => 'Alto Biobío']);
		DB::table('comunas')->insert(['codigo' => '03302', 'nombre' => 'Alto del Carmen']);
		DB::table('comunas')->insert(['codigo' => '01107', 'nombre' => 'Alto Hospicio']);
		DB::table('comunas')->insert(['codigo' => '10202', 'nombre' => 'Ancud']);
		DB::table('comunas')->insert(['codigo' => '04103', 'nombre' => 'Andacollo']);
		DB::table('comunas')->insert(['codigo' => '09201', 'nombre' => 'Angol']);
		DB::table('comunas')->insert(['codigo' => '12202', 'nombre' => 'Antártica']);
		DB::table('comunas')->insert(['codigo' => '02101', 'nombre' => 'Antofagasta']);
		DB::table('comunas')->insert(['codigo' => '08302', 'nombre' => 'Antuco']);
		DB::table('comunas')->insert(['codigo' => '08202', 'nombre' => 'Arauco']);
		DB::table('comunas')->insert(['codigo' => '15101', 'nombre' => 'Arica']);
		DB::table('comunas')->insert(['codigo' => '11201', 'nombre' => 'Aysén']);
		DB::table('comunas')->insert(['codigo' => '13402', 'nombre' => 'Buin']);
		DB::table('comunas')->insert(['codigo' => '08402', 'nombre' => 'Bulnes']);
		DB::table('comunas')->insert(['codigo' => '05402', 'nombre' => 'Cabildo']);
		DB::table('comunas')->insert(['codigo' => '12201', 'nombre' => 'Cabo de Hornos (Ex - Navarino)']);
		DB::table('comunas')->insert(['codigo' => '08303', 'nombre' => 'Cabrero']);
		DB::table('comunas')->insert(['codigo' => '02201', 'nombre' => 'Calama']);
		DB::table('comunas')->insert(['codigo' => '10102', 'nombre' => 'Calbuco']);
		DB::table('comunas')->insert(['codigo' => '03102', 'nombre' => 'Caldera']);
		DB::table('comunas')->insert(['codigo' => '05502', 'nombre' => 'Calera']);
		DB::table('comunas')->insert(['codigo' => '13403', 'nombre' => 'Calera de Tango']);
		DB::table('comunas')->insert(['codigo' => '05302', 'nombre' => 'Calle Larga']);
		DB::table('comunas')->insert(['codigo' => '15102', 'nombre' => 'Camarones']);
		DB::table('comunas')->insert(['codigo' => '01402', 'nombre' => 'Camiña']);
		DB::table('comunas')->insert(['codigo' => '04202', 'nombre' => 'Canela']);
		DB::table('comunas')->insert(['codigo' => '08203', 'nombre' => 'Cañete']);
		DB::table('comunas')->insert(['codigo' => '09102', 'nombre' => 'Carahue']);
		DB::table('comunas')->insert(['codigo' => '05603', 'nombre' => 'Cartagena']);
		DB::table('comunas')->insert(['codigo' => '05102', 'nombre' => 'Casablanca']);
		DB::table('comunas')->insert(['codigo' => '10201', 'nombre' => 'Castro']);
		DB::table('comunas')->insert(['codigo' => '05702', 'nombre' => 'Catemu']);
		DB::table('comunas')->insert(['codigo' => '07201', 'nombre' => 'Cauquenes']);
		DB::table('comunas')->insert(['codigo' => '13102', 'nombre' => 'Cerrillos']);
		DB::table('comunas')->insert(['codigo' => '13103', 'nombre' => 'Cerro Navia']);
		DB::table('comunas')->insert(['codigo' => '10401', 'nombre' => 'Chaitén']);
		DB::table('comunas')->insert(['codigo' => '07202', 'nombre' => 'Chanco']);
		DB::table('comunas')->insert(['codigo' => '03201', 'nombre' => 'Chañaral']);
		DB::table('comunas')->insert(['codigo' => '06302', 'nombre' => 'Chépica']);
		DB::table('comunas')->insert(['codigo' => '08103', 'nombre' => 'Chiguayante']);
		DB::table('comunas')->insert(['codigo' => '11401', 'nombre' => 'Chile Chico']);
		DB::table('comunas')->insert(['codigo' => '08401', 'nombre' => 'Chillán']);
		DB::table('comunas')->insert(['codigo' => '08406', 'nombre' => 'Chillán Viejo']);
		DB::table('comunas')->insert(['codigo' => '06303', 'nombre' => 'Chimbarongo']);
		DB::table('comunas')->insert(['codigo' => '09121', 'nombre' => 'Cholchol']);
		DB::table('comunas')->insert(['codigo' => '10203', 'nombre' => 'Chonchi']);
		DB::table('comunas')->insert(['codigo' => '11202', 'nombre' => 'Cisnes']);
		DB::table('comunas')->insert(['codigo' => '08403', 'nombre' => 'Cobquecura']);
		DB::table('comunas')->insert(['codigo' => '10103', 'nombre' => 'Cochamó']);
		DB::table('comunas')->insert(['codigo' => '11301', 'nombre' => 'Cochrane']);
		DB::table('comunas')->insert(['codigo' => '06102', 'nombre' => 'Codegua']);
		DB::table('comunas')->insert(['codigo' => '08404', 'nombre' => 'Coelemu']);
		DB::table('comunas')->insert(['codigo' => '08405', 'nombre' => 'Coihueco']);
		DB::table('comunas')->insert(['codigo' => '06103', 'nombre' => 'Coinco']);
		DB::table('comunas')->insert(['codigo' => '07402', 'nombre' => 'Colbún']);
		DB::table('comunas')->insert(['codigo' => '01403', 'nombre' => 'Colchane']);
		DB::table('comunas')->insert(['codigo' => '13301', 'nombre' => 'Colina']);
		DB::table('comunas')->insert(['codigo' => '09202', 'nombre' => 'Collipulli']);
		DB::table('comunas')->insert(['codigo' => '06104', 'nombre' => 'Coltauco']);
		DB::table('comunas')->insert(['codigo' => '04302', 'nombre' => 'Combarbalá']);
		DB::table('comunas')->insert(['codigo' => '08101', 'nombre' => 'Concepción']);
		DB::table('comunas')->insert(['codigo' => '13104', 'nombre' => 'Conchalí']);
		DB::table('comunas')->insert(['codigo' => '05103', 'nombre' => 'Concón']);
		DB::table('comunas')->insert(['codigo' => '07102', 'nombre' => 'Constitución']);
		DB::table('comunas')->insert(['codigo' => '08204', 'nombre' => 'Contulmo']);
		DB::table('comunas')->insert(['codigo' => '03101', 'nombre' => 'Copiapó']);
		DB::table('comunas')->insert(['codigo' => '04102', 'nombre' => 'Coquimbo']);
		DB::table('comunas')->insert(['codigo' => '08102', 'nombre' => 'Coronel']);
		DB::table('comunas')->insert(['codigo' => '14102', 'nombre' => 'Corral']);
		DB::table('comunas')->insert(['codigo' => '11101', 'nombre' => 'Coyhaique']);
		DB::table('comunas')->insert(['codigo' => '09103', 'nombre' => 'Cunco']);
		DB::table('comunas')->insert(['codigo' => '09203', 'nombre' => 'Curacautín']);
		DB::table('comunas')->insert(['codigo' => '13503', 'nombre' => 'Curacaví']);
		DB::table('comunas')->insert(['codigo' => '10204', 'nombre' => 'Curaco de Vélez']);
		DB::table('comunas')->insert(['codigo' => '08205', 'nombre' => 'Curanilahue']);
		DB::table('comunas')->insert(['codigo' => '09104', 'nombre' => 'Curarrehue']);
		DB::table('comunas')->insert(['codigo' => '07103', 'nombre' => 'Curepto']);
		DB::table('comunas')->insert(['codigo' => '07301', 'nombre' => 'Curicó']);
		DB::table('comunas')->insert(['codigo' => '10205', 'nombre' => 'Dalcahue']);
		DB::table('comunas')->insert(['codigo' => '03202', 'nombre' => 'Diego de Almagro']);
		DB::table('comunas')->insert(['codigo' => '06105', 'nombre' => 'Doñihue']);
		DB::table('comunas')->insert(['codigo' => '13105', 'nombre' => 'El Bosque']);
		DB::table('comunas')->insert(['codigo' => '08407', 'nombre' => 'El Carmen']);
		DB::table('comunas')->insert(['codigo' => '13602', 'nombre' => 'El Monte']);
		DB::table('comunas')->insert(['codigo' => '05604', 'nombre' => 'El Quisco']);
		DB::table('comunas')->insert(['codigo' => '05605', 'nombre' => 'El Tabo']);
		DB::table('comunas')->insert(['codigo' => '07104', 'nombre' => 'Empedrado']);
		DB::table('comunas')->insert(['codigo' => '09204', 'nombre' => 'Ercilla']);
		DB::table('comunas')->insert(['codigo' => '13106', 'nombre' => 'Estación Central']);
		DB::table('comunas')->insert(['codigo' => '08104', 'nombre' => 'Florida']);
		DB::table('comunas')->insert(['codigo' => '09105', 'nombre' => 'Freire']);
		DB::table('comunas')->insert(['codigo' => '03303', 'nombre' => 'Freirina']);
		DB::table('comunas')->insert(['codigo' => '10104', 'nombre' => 'Fresia']);
		DB::table('comunas')->insert(['codigo' => '10105', 'nombre' => 'Frutillar']);
		DB::table('comunas')->insert(['codigo' => '10402', 'nombre' => 'Futaleufú']);
		DB::table('comunas')->insert(['codigo' => '14202', 'nombre' => 'Futrono']);
		DB::table('comunas')->insert(['codigo' => '09106', 'nombre' => 'Galvarino']);
		DB::table('comunas')->insert(['codigo' => '15202', 'nombre' => 'General Lagos']);
		DB::table('comunas')->insert(['codigo' => '09107', 'nombre' => 'Gorbea']);
		DB::table('comunas')->insert(['codigo' => '06106', 'nombre' => 'Graneros']);
		DB::table('comunas')->insert(['codigo' => '11203', 'nombre' => 'Guaitecas']);
		DB::table('comunas')->insert(['codigo' => '05503', 'nombre' => 'Hijuelas']);
		DB::table('comunas')->insert(['codigo' => '10403', 'nombre' => 'Hualaihué']);
		DB::table('comunas')->insert(['codigo' => '07302', 'nombre' => 'Hualañé']);
		DB::table('comunas')->insert(['codigo' => '08112', 'nombre' => 'Hualpén']);
		DB::table('comunas')->insert(['codigo' => '08105', 'nombre' => 'Hualqui']);
		DB::table('comunas')->insert(['codigo' => '01404', 'nombre' => 'Huara']);
		DB::table('comunas')->insert(['codigo' => '03304', 'nombre' => 'Huasco']);
		DB::table('comunas')->insert(['codigo' => '13107', 'nombre' => 'Huechuraba']);
		DB::table('comunas')->insert(['codigo' => '04201', 'nombre' => 'Illapel']);
		DB::table('comunas')->insert(['codigo' => '13108', 'nombre' => 'Independencia']);
		DB::table('comunas')->insert(['codigo' => '01101', 'nombre' => 'Iquique']);
		DB::table('comunas')->insert(['codigo' => '13603', 'nombre' => 'Isla de Maipo']);
		DB::table('comunas')->insert(['codigo' => '05201', 'nombre' => 'Isla de Pascua']);
		DB::table('comunas')->insert(['codigo' => '05104', 'nombre' => 'Juan Fernández']);
		DB::table('comunas')->insert(['codigo' => '13109', 'nombre' => 'La Cisterna']);
		DB::table('comunas')->insert(['codigo' => '05504', 'nombre' => 'La Cruz']);
		DB::table('comunas')->insert(['codigo' => '06202', 'nombre' => 'La Estrella']);
		DB::table('comunas')->insert(['codigo' => '13110', 'nombre' => 'La Florida']);
		DB::table('comunas')->insert(['codigo' => '13111', 'nombre' => 'La Granja']);
		DB::table('comunas')->insert(['codigo' => '04104', 'nombre' => 'La Higuera']);
		DB::table('comunas')->insert(['codigo' => '05401', 'nombre' => 'La Ligua']);
		DB::table('comunas')->insert(['codigo' => '13112', 'nombre' => 'La Pintana']);
		DB::table('comunas')->insert(['codigo' => '13113', 'nombre' => 'La Reina']);
		DB::table('comunas')->insert(['codigo' => '04101', 'nombre' => 'La Serena']);
		DB::table('comunas')->insert(['codigo' => '14201', 'nombre' => 'La Unión']);
		DB::table('comunas')->insert(['codigo' => '14203', 'nombre' => 'Lago Ranco']);
		DB::table('comunas')->insert(['codigo' => '11102', 'nombre' => 'Lago Verde']);
		DB::table('comunas')->insert(['codigo' => '12102', 'nombre' => 'Laguna Blanca']);
		DB::table('comunas')->insert(['codigo' => '08304', 'nombre' => 'Laja']);
		DB::table('comunas')->insert(['codigo' => '13302', 'nombre' => 'Lampa ']);
		DB::table('comunas')->insert(['codigo' => '14103', 'nombre' => 'Lanco']);
		DB::table('comunas')->insert(['codigo' => '06107', 'nombre' => 'Las Cabras']);
		DB::table('comunas')->insert(['codigo' => '13114', 'nombre' => 'Las Condes']);
		DB::table('comunas')->insert(['codigo' => '09108', 'nombre' => 'Lautaro']);
		DB::table('comunas')->insert(['codigo' => '08201', 'nombre' => 'Lebu']);
		DB::table('comunas')->insert(['codigo' => '07303', 'nombre' => 'Licantén']);
		DB::table('comunas')->insert(['codigo' => '05802', 'nombre' => 'Limache']);
		DB::table('comunas')->insert(['codigo' => '07401', 'nombre' => 'Linares']);
		DB::table('comunas')->insert(['codigo' => '06203', 'nombre' => 'Litueche']);
		DB::table('comunas')->insert(['codigo' => '05703', 'nombre' => 'Llaillay']);
		DB::table('comunas')->insert(['codigo' => '10107', 'nombre' => 'Llanquihue']);
		DB::table('comunas')->insert(['codigo' => '13115', 'nombre' => 'Lo Barnechea']);
		DB::table('comunas')->insert(['codigo' => '13116', 'nombre' => 'Lo Espejo']);
		DB::table('comunas')->insert(['codigo' => '13117', 'nombre' => 'Lo Prado']);
		DB::table('comunas')->insert(['codigo' => '06304', 'nombre' => 'Lolol']);
		DB::table('comunas')->insert(['codigo' => '09109', 'nombre' => 'Loncoche']);
		DB::table('comunas')->insert(['codigo' => '07403', 'nombre' => 'Longaví']);
		DB::table('comunas')->insert(['codigo' => '09205', 'nombre' => 'Lonquimay']);
		DB::table('comunas')->insert(['codigo' => '08206', 'nombre' => 'Los Álamos']);
		DB::table('comunas')->insert(['codigo' => '05301', 'nombre' => 'Los Andes']);
		DB::table('comunas')->insert(['codigo' => '08301', 'nombre' => 'Los Ángeles']);
		DB::table('comunas')->insert(['codigo' => '14104', 'nombre' => 'Los Lagos']);
		DB::table('comunas')->insert(['codigo' => '10106', 'nombre' => 'Los Muermos']);
		DB::table('comunas')->insert(['codigo' => '09206', 'nombre' => 'Los Sauces']);
		DB::table('comunas')->insert(['codigo' => '04203', 'nombre' => 'Los Vilos']);
		DB::table('comunas')->insert(['codigo' => '08106', 'nombre' => 'Lota']);
		DB::table('comunas')->insert(['codigo' => '09207', 'nombre' => 'Lumaco']);
		DB::table('comunas')->insert(['codigo' => '06108', 'nombre' => 'Machalí']);
		DB::table('comunas')->insert(['codigo' => '13118', 'nombre' => 'Macul']);
		DB::table('comunas')->insert(['codigo' => '14105', 'nombre' => 'Máfil']);
		DB::table('comunas')->insert(['codigo' => '13119', 'nombre' => 'Maipú']);
		DB::table('comunas')->insert(['codigo' => '06109', 'nombre' => 'Malloa']);
		DB::table('comunas')->insert(['codigo' => '06204', 'nombre' => 'Marchihue']);
		DB::table('comunas')->insert(['codigo' => '02302', 'nombre' => 'María Elena']);
		DB::table('comunas')->insert(['codigo' => '13504', 'nombre' => 'María Pinto']);
		DB::table('comunas')->insert(['codigo' => '14106', 'nombre' => 'Mariquina']);
		DB::table('comunas')->insert(['codigo' => '07105', 'nombre' => 'Maule']);
		DB::table('comunas')->insert(['codigo' => '10108', 'nombre' => 'Maullín']);
		DB::table('comunas')->insert(['codigo' => '02102', 'nombre' => 'Mejillones']);
		DB::table('comunas')->insert(['codigo' => '09110', 'nombre' => 'Melipeuco']);
		DB::table('comunas')->insert(['codigo' => '13501', 'nombre' => 'Melipilla']);
		DB::table('comunas')->insert(['codigo' => '07304', 'nombre' => 'Molina']);
		DB::table('comunas')->insert(['codigo' => '04303', 'nombre' => 'Monte Patria']);
		DB::table('comunas')->insert(['codigo' => '06110', 'nombre' => 'Mostazal']);
		DB::table('comunas')->insert(['codigo' => '08305', 'nombre' => 'Mulchén']);
		DB::table('comunas')->insert(['codigo' => '08306', 'nombre' => 'Nacimiento']);
		DB::table('comunas')->insert(['codigo' => '06305', 'nombre' => 'Nancagua']);
		DB::table('comunas')->insert(['codigo' => '12401', 'nombre' => 'Natales']);
		DB::table('comunas')->insert(['codigo' => '06205', 'nombre' => 'Navidad']);
		DB::table('comunas')->insert(['codigo' => '08307', 'nombre' => 'Negrete']);
		DB::table('comunas')->insert(['codigo' => '08408', 'nombre' => 'Ninhue']);
		DB::table('comunas')->insert(['codigo' => '05506', 'nombre' => 'Nogales']);
		DB::table('comunas')->insert(['codigo' => '09111', 'nombre' => 'Nueva Imperial']);
		DB::table('comunas')->insert(['codigo' => '08409', 'nombre' => 'Ñiquén']);
		DB::table('comunas')->insert(['codigo' => '13120', 'nombre' => 'Ñuñoa']);
		DB::table('comunas')->insert(['codigo' => '11302', 'nombre' => 'O’Higgins']);
		DB::table('comunas')->insert(['codigo' => '06111', 'nombre' => 'Olivar']);
		DB::table('comunas')->insert(['codigo' => '02202', 'nombre' => 'Ollagüe']);
		DB::table('comunas')->insert(['codigo' => '05803', 'nombre' => 'Olmué']);
		DB::table('comunas')->insert(['codigo' => '10301', 'nombre' => 'Osorno']);
		DB::table('comunas')->insert(['codigo' => '04301', 'nombre' => 'Ovalle']);
		DB::table('comunas')->insert(['codigo' => '13604', 'nombre' => 'Padre Hurtado']);
		DB::table('comunas')->insert(['codigo' => '09112', 'nombre' => 'Padre Las Casas']);
		DB::table('comunas')->insert(['codigo' => '04105', 'nombre' => 'Paiguano']);
		DB::table('comunas')->insert(['codigo' => '14107', 'nombre' => 'Paillaco']);
		DB::table('comunas')->insert(['codigo' => '13404', 'nombre' => 'Paine']);
		DB::table('comunas')->insert(['codigo' => '10404', 'nombre' => 'Palena']);
		DB::table('comunas')->insert(['codigo' => '06306', 'nombre' => 'Palmilla']);
		DB::table('comunas')->insert(['codigo' => '14108', 'nombre' => 'Panguipulli']);
		DB::table('comunas')->insert(['codigo' => '05704', 'nombre' => 'Panquehue']);
		DB::table('comunas')->insert(['codigo' => '05403', 'nombre' => 'Papudo']);
		DB::table('comunas')->insert(['codigo' => '06206', 'nombre' => 'Paredones']);
		DB::table('comunas')->insert(['codigo' => '07404', 'nombre' => 'Parral']);
		DB::table('comunas')->insert(['codigo' => '13121', 'nombre' => 'Pedro Aguirre Cerda']);
		DB::table('comunas')->insert(['codigo' => '07106', 'nombre' => 'Pelarco']);
		DB::table('comunas')->insert(['codigo' => '07203', 'nombre' => 'Pelluhue']);
		DB::table('comunas')->insert(['codigo' => '08410', 'nombre' => 'Pemuco']);
		DB::table('comunas')->insert(['codigo' => '07107', 'nombre' => 'Pencahue']);
		DB::table('comunas')->insert(['codigo' => '08107', 'nombre' => 'Penco']);
		DB::table('comunas')->insert(['codigo' => '13605', 'nombre' => 'Peñaflor']);
		DB::table('comunas')->insert(['codigo' => '13122', 'nombre' => 'Peñalolén']);
		DB::table('comunas')->insert(['codigo' => '06307', 'nombre' => 'Peralillo']);
		DB::table('comunas')->insert(['codigo' => '09113', 'nombre' => 'Perquenco']);
		DB::table('comunas')->insert(['codigo' => '05404', 'nombre' => 'Petorca']);
		DB::table('comunas')->insert(['codigo' => '06112', 'nombre' => 'Peumo']);
		DB::table('comunas')->insert(['codigo' => '01405', 'nombre' => 'Pica']);
		DB::table('comunas')->insert(['codigo' => '06113', 'nombre' => 'Pichidegua']);
		DB::table('comunas')->insert(['codigo' => '06201', 'nombre' => 'Pichilemu']);
		DB::table('comunas')->insert(['codigo' => '08411', 'nombre' => 'Pinto']);
		DB::table('comunas')->insert(['codigo' => '13202', 'nombre' => 'Pirque']);
		DB::table('comunas')->insert(['codigo' => '09114', 'nombre' => 'Pitrufquén']);
		DB::table('comunas')->insert(['codigo' => '06308', 'nombre' => 'Placilla']);
		DB::table('comunas')->insert(['codigo' => '08412', 'nombre' => 'Portezuelo']);
		DB::table('comunas')->insert(['codigo' => '12301', 'nombre' => 'Porvenir']);
		DB::table('comunas')->insert(['codigo' => '01401', 'nombre' => 'Pozo Almonte']);
		DB::table('comunas')->insert(['codigo' => '12302', 'nombre' => 'Primavera']);
		DB::table('comunas')->insert(['codigo' => '13123', 'nombre' => 'Providencia']);
		DB::table('comunas')->insert(['codigo' => '05105', 'nombre' => 'Puchuncaví']);
		DB::table('comunas')->insert(['codigo' => '09115', 'nombre' => 'Pucón']);
		DB::table('comunas')->insert(['codigo' => '13124', 'nombre' => 'Pudahuel']);
		DB::table('comunas')->insert(['codigo' => '13201', 'nombre' => 'Puente Alto']);
		DB::table('comunas')->insert(['codigo' => '10101', 'nombre' => 'Puerto Montt']);
		DB::table('comunas')->insert(['codigo' => '10302', 'nombre' => 'Puerto Octay']);
		DB::table('comunas')->insert(['codigo' => '10109', 'nombre' => 'Puerto Varas']);
		DB::table('comunas')->insert(['codigo' => '06309', 'nombre' => 'Pumanque']);
		DB::table('comunas')->insert(['codigo' => '04304', 'nombre' => 'Punitaqui']);
		DB::table('comunas')->insert(['codigo' => '12101', 'nombre' => 'Punta Arenas']);
		DB::table('comunas')->insert(['codigo' => '10206', 'nombre' => 'Puqueldón']);
		DB::table('comunas')->insert(['codigo' => '09208', 'nombre' => 'Purén']);
		DB::table('comunas')->insert(['codigo' => '10303', 'nombre' => 'Purranque']);
		DB::table('comunas')->insert(['codigo' => '05705', 'nombre' => 'Putaendo']);
		DB::table('comunas')->insert(['codigo' => '15201', 'nombre' => 'Putre']);
		DB::table('comunas')->insert(['codigo' => '10304', 'nombre' => 'Puyehue']);
		DB::table('comunas')->insert(['codigo' => '10207', 'nombre' => 'Queilén']);
		DB::table('comunas')->insert(['codigo' => '10208', 'nombre' => 'Quellón']);
		DB::table('comunas')->insert(['codigo' => '10209', 'nombre' => 'Quemchi']);
		DB::table('comunas')->insert(['codigo' => '08308', 'nombre' => 'Quilaco']);
		DB::table('comunas')->insert(['codigo' => '13125', 'nombre' => 'Quilicura']);
		DB::table('comunas')->insert(['codigo' => '08309', 'nombre' => 'Quilleco']);
		DB::table('comunas')->insert(['codigo' => '08413', 'nombre' => 'Quillón']);
		DB::table('comunas')->insert(['codigo' => '05501', 'nombre' => 'Quillota']);
		DB::table('comunas')->insert(['codigo' => '05801', 'nombre' => 'Quilpué']);
		DB::table('comunas')->insert(['codigo' => '10210', 'nombre' => 'Quinchao']);
		DB::table('comunas')->insert(['codigo' => '06114', 'nombre' => 'Quinta de Tilcoco']);
		DB::table('comunas')->insert(['codigo' => '13126', 'nombre' => 'Quinta Normal']);
		DB::table('comunas')->insert(['codigo' => '05107', 'nombre' => 'Quintero']);
		DB::table('comunas')->insert(['codigo' => '08414', 'nombre' => 'Quirihue']);
		DB::table('comunas')->insert(['codigo' => '06101', 'nombre' => 'Rancagua']);
		DB::table('comunas')->insert(['codigo' => '08415', 'nombre' => 'Ránquil']);
		DB::table('comunas')->insert(['codigo' => '07305', 'nombre' => 'Rauco']);
		DB::table('comunas')->insert(['codigo' => '13127', 'nombre' => 'Recoleta']);
		DB::table('comunas')->insert(['codigo' => '09209', 'nombre' => 'Renaico']);
		DB::table('comunas')->insert(['codigo' => '13128', 'nombre' => 'Renca']);
		DB::table('comunas')->insert(['codigo' => '06115', 'nombre' => 'Rengo']);
		DB::table('comunas')->insert(['codigo' => '06116', 'nombre' => 'Requínoa']);
		DB::table('comunas')->insert(['codigo' => '07405', 'nombre' => 'Retiro']);
		DB::table('comunas')->insert(['codigo' => '05303', 'nombre' => 'Rinconada']);
		DB::table('comunas')->insert(['codigo' => '14204', 'nombre' => 'Río Bueno']);
		DB::table('comunas')->insert(['codigo' => '07108', 'nombre' => 'Río Claro']);
		DB::table('comunas')->insert(['codigo' => '04305', 'nombre' => 'Río Hurtado']);
		DB::table('comunas')->insert(['codigo' => '11402', 'nombre' => 'Río Ibáñez']);
		DB::table('comunas')->insert(['codigo' => '10305', 'nombre' => 'Río Negro']);
		DB::table('comunas')->insert(['codigo' => '12103', 'nombre' => 'Río Verde']);
		DB::table('comunas')->insert(['codigo' => '07306', 'nombre' => 'Romeral']);
		DB::table('comunas')->insert(['codigo' => '09116', 'nombre' => 'Saavedra']);
		DB::table('comunas')->insert(['codigo' => '07307', 'nombre' => 'Sagrada Familia']);
		DB::table('comunas')->insert(['codigo' => '04204', 'nombre' => 'Salamanca']);
		DB::table('comunas')->insert(['codigo' => '05601', 'nombre' => 'San Antonio']);
		DB::table('comunas')->insert(['codigo' => '13401', 'nombre' => 'San Bernardo']);
		DB::table('comunas')->insert(['codigo' => '08416', 'nombre' => 'San Carlos']);
		DB::table('comunas')->insert(['codigo' => '07109', 'nombre' => 'San Clemente']);
		DB::table('comunas')->insert(['codigo' => '05304', 'nombre' => 'San Esteban']);
		DB::table('comunas')->insert(['codigo' => '08417', 'nombre' => 'San Fabián']);
		DB::table('comunas')->insert(['codigo' => '05701', 'nombre' => 'San Felipe']);
		DB::table('comunas')->insert(['codigo' => '06301', 'nombre' => 'San Fernando']);
		DB::table('comunas')->insert(['codigo' => '12104', 'nombre' => 'San Gregorio']);
		DB::table('comunas')->insert(['codigo' => '08418', 'nombre' => 'San Ignacio']);
		DB::table('comunas')->insert(['codigo' => '07406', 'nombre' => 'San Javier']);
		DB::table('comunas')->insert(['codigo' => '13129', 'nombre' => 'San Joaquín']);
		DB::table('comunas')->insert(['codigo' => '13203', 'nombre' => 'San José de Maipo']);
		DB::table('comunas')->insert(['codigo' => '10306', 'nombre' => 'San Juan de la Costa']);
		DB::table('comunas')->insert(['codigo' => '13130', 'nombre' => 'San Miguel']);
		DB::table('comunas')->insert(['codigo' => '08419', 'nombre' => 'San Nicolás']);
		DB::table('comunas')->insert(['codigo' => '10307', 'nombre' => 'San Pablo']);
		DB::table('comunas')->insert(['codigo' => '13505', 'nombre' => 'San Pedro']);
		DB::table('comunas')->insert(['codigo' => '02203', 'nombre' => 'San Pedro de Atacama']);
		DB::table('comunas')->insert(['codigo' => '08108', 'nombre' => 'San Pedro de la Paz']);
		DB::table('comunas')->insert(['codigo' => '07110', 'nombre' => 'San Rafael']);
		DB::table('comunas')->insert(['codigo' => '13131', 'nombre' => 'San Ramón']);
		DB::table('comunas')->insert(['codigo' => '08310', 'nombre' => 'San Rosendo']);
		DB::table('comunas')->insert(['codigo' => '06117', 'nombre' => 'San Vicente']);
		DB::table('comunas')->insert(['codigo' => '08311', 'nombre' => 'Santa Bárbara']);
		DB::table('comunas')->insert(['codigo' => '06310', 'nombre' => 'Santa Cruz']);
		DB::table('comunas')->insert(['codigo' => '08109', 'nombre' => 'Santa Juana']);
		DB::table('comunas')->insert(['codigo' => '05706', 'nombre' => 'Santa María']);
		DB::table('comunas')->insert(['codigo' => '13101', 'nombre' => 'Santiago']);
		DB::table('comunas')->insert(['codigo' => '05606', 'nombre' => 'Santo Domingo']);
		DB::table('comunas')->insert(['codigo' => '02103', 'nombre' => 'Sierra Gorda']);
		DB::table('comunas')->insert(['codigo' => '13601', 'nombre' => 'Talagante']);
		DB::table('comunas')->insert(['codigo' => '07101', 'nombre' => 'Talca']);
		DB::table('comunas')->insert(['codigo' => '08110', 'nombre' => 'Talcahuano']);
		DB::table('comunas')->insert(['codigo' => '02104', 'nombre' => 'Taltal']);
		DB::table('comunas')->insert(['codigo' => '09101', 'nombre' => 'Temuco']);
		DB::table('comunas')->insert(['codigo' => '07308', 'nombre' => 'Teno']);
		DB::table('comunas')->insert(['codigo' => '09117', 'nombre' => 'Teodoro Schmidt']);
		DB::table('comunas')->insert(['codigo' => '03103', 'nombre' => 'Tierra Amarilla']);
		DB::table('comunas')->insert(['codigo' => '13303', 'nombre' => 'Tiltil']);
		DB::table('comunas')->insert(['codigo' => '12303', 'nombre' => 'Timaukel']);
		DB::table('comunas')->insert(['codigo' => '08207', 'nombre' => 'Tirúa']);
		DB::table('comunas')->insert(['codigo' => '02301', 'nombre' => 'Tocopilla']);
		DB::table('comunas')->insert(['codigo' => '09118', 'nombre' => 'Toltén']);
		DB::table('comunas')->insert(['codigo' => '08111', 'nombre' => 'Tomé']);
		DB::table('comunas')->insert(['codigo' => '12402', 'nombre' => 'Torres del Paine']);
		DB::table('comunas')->insert(['codigo' => '11303', 'nombre' => 'Tortel']);
		DB::table('comunas')->insert(['codigo' => '09210', 'nombre' => 'Traiguén']);
		DB::table('comunas')->insert(['codigo' => '08420', 'nombre' => 'Treguaco']);
		DB::table('comunas')->insert(['codigo' => '08312', 'nombre' => 'Tucapel']);
		DB::table('comunas')->insert(['codigo' => '14101', 'nombre' => 'Valdivia']);
		DB::table('comunas')->insert(['codigo' => '03301', 'nombre' => 'Vallenar']);
		DB::table('comunas')->insert(['codigo' => '05101', 'nombre' => 'Valparaíso']);
		DB::table('comunas')->insert(['codigo' => '07309', 'nombre' => 'Vichuquén']);
		DB::table('comunas')->insert(['codigo' => '09211', 'nombre' => 'Victoria']);
		DB::table('comunas')->insert(['codigo' => '04106', 'nombre' => 'Vicuña']);
		DB::table('comunas')->insert(['codigo' => '09119', 'nombre' => 'Vilcún']);
		DB::table('comunas')->insert(['codigo' => '07407', 'nombre' => 'Villa Alegre']);
		DB::table('comunas')->insert(['codigo' => '05804', 'nombre' => 'Villa Alemana']);
		DB::table('comunas')->insert(['codigo' => '09120', 'nombre' => 'Villarrica']);
		DB::table('comunas')->insert(['codigo' => '05109', 'nombre' => 'Viña del Mar']);
		DB::table('comunas')->insert(['codigo' => '13132', 'nombre' => 'Vitacura']);
		DB::table('comunas')->insert(['codigo' => '07408', 'nombre' => 'Yerbas Buenas']);
		DB::table('comunas')->insert(['codigo' => '08313', 'nombre' => 'Yumbel']);
		DB::table('comunas')->insert(['codigo' => '08421', 'nombre' => 'Yungay']);
		DB::table('comunas')->insert(['codigo' => '05405', 'nombre' => 'Zapallar']);
	}
}